# Generated by Django 3.2.4 on 2021-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='cairo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='zip',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
