# Generated by Django 3.2.4 on 2021-06-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userfollowedstocks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollowedStocks',
        ),
    ]
